### ISSUE TITLE
Dont get action name with set alias on route

### ISSUE THREAD

**Issue by renanbirlem** [muhammadshakeel/laravel-api-boilerplate-oauth#3]
When we put an alias on the route, the route api listing is no longer displayed the "action", but the term "Closure".

For example:

```
$api->get('users', 
         ['as' => 'users.list', 
          'uses' => 'App\Api\V1\Controllers\UserController@index']);
```

Display in route list:

```
URI:  GET|HEAD /v1/users 
Name: users.list
Action: Closure
```

**Comment by muhammadshakeel** [comment]
Seems related to the following issue as we have used [dingo/api](https://github.com/dingo/api):

https://github.com/dingo/api/pull/871

**Comment by renanbirlem** [comment]
I already have this fix does not solve the problem. In this case they are not using the alias of routes. The problem only occurs when you put the alias ('uses = "foo"')

**Comment by renanbirlem** [comment]
See the difference...

![captura de tela 2016-03-24 as 12 43 19](https://cloud.githubusercontent.com/assets/13525605/14022314/02e9d376-f1be-11e5-8c67-143d4eddc113.png)

**Comment by renanbirlem** [comment]
When have a named route, display "Closure"

**Comment by muhammadshakeel** [comment]
@renanbirlem I have just updated dingo/api and the issue is resolved:

![named-route-list](https://cloud.githubusercontent.com/assets/4094268/14038767/e120e054-f276-11e5-9101-d72c1dc94ec8.png)

kindly run composer update, the issue will be resolved.

**Comment by renanbirlem** [comment]
Can you send me your route declaration? With alias...
I run the command and nothing happened.

**Comment by muhammadshakeel** [comment]
Following is a named route declaration, seems like you are not using 'as' keyword:

```
$api->get('reset-password/{token}/{username}', ['as' => 'reset.password', 'uses' => 'App\Api\v1\Controllers\AuthController@resetPassword']);
```

After updating dingo/api this must work.
